# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jzapata
      MONGO_INITDB_ROOT_PASSWORD: jzapata
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jzapata
      ME_CONFIG_MONGODB_ADMINPASSWORD: jzapata
      ME_CONFIG_MONGODB_URL: mongodb://jzapata:jzapata@mongo:27017/
